#!/bin/bash

set -e

if [ $# -lt 2 ]; then
    echo "Usage: $0 number_of_elevators top_floor" >&2
    exit 1
fi

number_of_elevators=$1
top_floor=$2

java -classpath lib/elevator.jar elevator.Elevators -tcp -number $number_of_elevators -top $top_floor &
while ! netstat -tln | grep -q ":4711"; do sleep 1; done
java -classpath bin se.kth.id1217.Main localhost 4711 $number_of_elevators
